language: node_js

node_js:
  - "14.15.4"

cache:
  directories:
  - node_modules

script:
  - npm run docs

before_deploy:
  - npm run test -- --coverage || travis_terminate 1
  - npm run build
  - npm run build:ff

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: pages
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file:
      - firefox.zip
      - $zip
    on:
      tags: true

after_deploy:
  - if [ ! -z  "$TRAVIS_TAG" ]; then
      npx cws-upload $cid $sec $tkn $zip $eid;
      cd dist-ff && npx web-ext-submit --api-key=$ff_key --api-secret=$ff_secret && cd ..;
    fi
